create schema WEB_FINAL_PROJECT

default character set utf8;

use WEB_FINAL_PROJECT;


CREATE TABLE `WEB_FINAL_PROJECT`.`USER_TYPES` (
    `ID` INT NOT NULL,
    `NAME` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `WEB_FINAL_PROJECT`.`USERS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(45) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `FIRSTNAME` VARCHAR(45) NOT NULL,
    `LASTNAME` VARCHAR(45) NOT NULL,
    `EMAIL` VARCHAR(45) NOT NULL,
    `TYPE_ID` INT NOT NULL,
    
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
    INDEX `fk_USERS_TO_TYPES_idx` (`TYPE_ID` ASC),
    CONSTRAINT `fk_USERS_TO_TYPES` FOREIGN KEY (`TYPE_ID`)
        REFERENCES `WEB_FINAL_PROJECT`.`USER_TYPES` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

INSERT INTO `USER_TYPES`(`ID`, `NAME`) VALUES (1, 'USER');
INSERT INTO `USER_TYPES`(`ID`, `NAME`) VALUES (2, 'ADMIN');

INSERT INTO `USERS`(`ID`, `USERNAME`, `PASSWORD`, `FIRSTNAME`, `LASTNAME`, `EMAIL`, `TYPE_ID`)
    VALUES (1, 'levan9', '123', 'Levan', 'Karanadze', 'levan@gmail.com', 1);
                            
                            
select * from USERS;


CREATE TABLE `WEB_FINAL_PROJECT`.`GAMES` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `ROUND` INT NOT NULL,
    `TEAM1` VARCHAR(100) NOT NULL,
    `TEAM2` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `WEB_FINAL_PROJECT`.`RESULTS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
	`GAME_ID` INT NOT NULL,
    `RESULT` INT NOT NULL,
    PRIMARY KEY (`ID`),
	CONSTRAINT `fk_RESULTS_TO_GAMES` FOREIGN KEY (`GAME_ID`)
        REFERENCES `WEB_FINAL_PROJECT`.`GAMES` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE `WEB_FINAL_PROJECT`.`PREDICTIONS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
	`GAME_ID` INT NOT NULL,
    `PREDICTION` INT NOT NULL,
    `USER_ID` INT NOT NULL,
    PRIMARY KEY (`ID`),
	CONSTRAINT `fk_PREDICTIONS_TO_GAMES` FOREIGN KEY (`GAME_ID`)
        REFERENCES `WEB_FINAL_PROJECT`.`GAMES` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `fk_PREDICTIONS_TO_USERS` FOREIGN KEY (`USER_ID`)
        REFERENCES `WEB_FINAL_PROJECT`.`USERS` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE `WEB_FINAL_PROJECT`.`USER_HISTORY` (
    `ID` INT NOT NULL AUTO_INCREMENT,
	`USER_ID` INT NOT NULL,
    `ROUND_ID` INT NOT NULL,
    `SCORE` INT NOT NULL,
    PRIMARY KEY (`ID`),
	CONSTRAINT `fk_USER_HISTORY_TO_GAMES` FOREIGN KEY (`ROUND_ID`)
        REFERENCES `WEB_FINAL_PROJECT`.`GAMES` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION,
	CONSTRAINT `fk_USER_HISTORY_TO_USERS` FOREIGN KEY (`USER_ID`)
        REFERENCES `WEB_FINAL_PROJECT`.`USERS` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

















