create schema WEB_FINAL_PROJECT

default character set utf8;

use WEB_FINAL_PROJECT;


CREATE TABLE `WEB_FINAL_PROJECT`.`USER_TYPES` (
    `ID` INT NOT NULL,
    `NAME` VARCHAR(45) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE `WEB_FINAL_PROJECT`.`USERS` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `USERNAME` VARCHAR(45) NOT NULL,
    `PASSWORD` VARCHAR(100) NOT NULL,
    `FIRSTNAME` VARCHAR(45) NOT NULL,
    `LASTNAME` VARCHAR(45) NOT NULL,
    `EMAIL` VARCHAR(45) NOT NULL,
    `TYPE_ID` INT NOT NULL,
    PRIMARY KEY (`ID`),
    UNIQUE INDEX `USERNAME_UNIQUE` (`USERNAME` ASC),
    INDEX `fk_USERS_TO_TYPES_idx` (`TYPE_ID` ASC),
    CONSTRAINT `fk_USERS_TO_TYPES` FOREIGN KEY (`TYPE_ID`)
        REFERENCES `WEB_FINAL_PROJECT`.`USER_TYPES` (`ID`)
        ON DELETE NO ACTION ON UPDATE NO ACTION
);

INSERT INTO `USER_TYPES`(`ID`, `NAME`) VALUES (1, 'USER');
INSERT INTO `USER_TYPES`(`ID`, `NAME`) VALUES (2, 'ADMIN');

INSERT INTO `USERS`(`ID`, `USERNAME`, `PASSWORD`, `FIRSTNAME`, `LASTNAME`, `EMAIL`, `TYPE_ID`)
    VALUES (1, 'levan9', '123', 'Levan', 'Karanadze', 'levan@gmail.com', 1);
                            
                            
select * from USERS;